name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with GCR
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcloud.json
        cat /tmp/gcloud.json | docker login -u _json_key --password-stdin https://gcr.io

    - name: Configure gcloud account
      run: |
        gcloud auth activate-service-account --key-file=/tmp/gcloud.json
        gcloud config set account $(gcloud auth list --format="value(account)" --filter="status:ACTIVE")

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:$GITHUB_SHA .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
